// <auto-generated />
using System;
using BackPredio11.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackPredio11.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241017003525_MudandoBemParaItem")]
    partial class MudandoBemParaItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackPredio11.Entities.Item", b =>
                {
                    b.Property<long>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ItemId"));

                    b.Property<string>("ItemDescricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemPermitido")
                        .HasColumnType("integer");

                    b.Property<long>("StatusItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("TipoItemId")
                        .HasColumnType("bigint");

                    b.HasKey("ItemId");

                    b.HasIndex("StatusItemId");

                    b.HasIndex("TipoItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("BackPredio11.Entities.MotivoRetirada", b =>
                {
                    b.Property<long>("MotivoRetiradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MotivoRetiradaId"));

                    b.Property<string>("MotivoDescricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MotivoRetiradaId");

                    b.ToTable("Motivos");
                });

            modelBuilder.Entity("BackPredio11.Entities.Pessoa", b =>
                {
                    b.Property<long>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PessoaId"));

                    b.Property<string>("PessoaIdUnivates")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PessoaNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PessoaSenha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PessoaTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PessoaId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("BackPredio11.Entities.Reserva", b =>
                {
                    b.Property<long>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReservaId"));

                    b.Property<long>("BemId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<int>("QuantidadeBem")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReservaData")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReservaDataValidade")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ReservaId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("BackPredio11.Entities.Retirada", b =>
                {
                    b.Property<long>("RetiradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RetiradaId"));

                    b.Property<long>("BemId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DevolucaoData")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LimiteData")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MotivoRetiradaId")
                        .HasColumnType("bigint");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<int>("QuantidadeBem")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RetiradaData")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RetiradaDescricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RetiradaId");

                    b.HasIndex("ItemId");

                    b.HasIndex("MotivoRetiradaId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Retiradas");
                });

            modelBuilder.Entity("BackPredio11.Entities.StatusItem", b =>
                {
                    b.Property<long>("StatusItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StatusItemId"));

                    b.Property<string>("ItemDescricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StatusItemId");

                    b.ToTable("StatusItems");
                });

            modelBuilder.Entity("BackPredio11.Entities.TipoItem", b =>
                {
                    b.Property<long>("TipoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TipoItemId"));

                    b.Property<string>("ItemDescricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TipoItemId");

                    b.ToTable("TipoItems");
                });

            modelBuilder.Entity("BackPredio11.Entities.Item", b =>
                {
                    b.HasOne("BackPredio11.Entities.StatusItem", "StatusItem")
                        .WithMany("Items")
                        .HasForeignKey("StatusItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackPredio11.Entities.TipoItem", "TipoItem")
                        .WithMany("Items")
                        .HasForeignKey("TipoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusItem");

                    b.Navigation("TipoItem");
                });

            modelBuilder.Entity("BackPredio11.Entities.Reserva", b =>
                {
                    b.HasOne("BackPredio11.Entities.Item", "Item")
                        .WithMany("Reservas")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackPredio11.Entities.Pessoa", "Pessoa")
                        .WithMany("Reservas")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("BackPredio11.Entities.Retirada", b =>
                {
                    b.HasOne("BackPredio11.Entities.Item", "Item")
                        .WithMany("Retiradas")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackPredio11.Entities.MotivoRetirada", "MotivoRetirada")
                        .WithMany("Retiradas")
                        .HasForeignKey("MotivoRetiradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackPredio11.Entities.Pessoa", "Pessoa")
                        .WithMany("Retiradas")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("MotivoRetirada");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("BackPredio11.Entities.Item", b =>
                {
                    b.Navigation("Reservas");

                    b.Navigation("Retiradas");
                });

            modelBuilder.Entity("BackPredio11.Entities.MotivoRetirada", b =>
                {
                    b.Navigation("Retiradas");
                });

            modelBuilder.Entity("BackPredio11.Entities.Pessoa", b =>
                {
                    b.Navigation("Reservas");

                    b.Navigation("Retiradas");
                });

            modelBuilder.Entity("BackPredio11.Entities.StatusItem", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BackPredio11.Entities.TipoItem", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
