// <auto-generated />
using System;
using BackPredio11.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackPredio11.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240929222219_CriandoTabelaReserva")]
    partial class CriandoTabelaReserva
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackPredio11.Entities.MotivoRetirada", b =>
                {
                    b.Property<long>("MotivoRetiradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MotivoRetiradaId"));

                    b.Property<string>("MotivoDescricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MotivoRetiradaId");

                    b.ToTable("Motivos");
                });

            modelBuilder.Entity("BackPredio11.Entities.Pessoa", b =>
                {
                    b.Property<long>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PessoaId"));

                    b.Property<string>("PessoaIdUnivates")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PessoaNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PessoaTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PessoaId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("BackPredio11.Entities.Reserva", b =>
                {
                    b.Property<long>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReservaId"));

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<int>("QuantidadeBem")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReservaData")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReservaDataValidade")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ReservaId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("BackPredio11.Entities.Retirada", b =>
                {
                    b.Property<long>("RetiradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RetiradaId"));

                    b.Property<DateTime>("DevolucaoData")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LimiteData")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MotivoRetiradaId")
                        .HasColumnType("bigint");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<int>("QuantidadeBem")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RetiradaData")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RetiradaDescricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RetiradaId");

                    b.HasIndex("MotivoRetiradaId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Retiradas");
                });

            modelBuilder.Entity("BackPredio11.Entities.Reserva", b =>
                {
                    b.HasOne("BackPredio11.Entities.Pessoa", "Pessoa")
                        .WithMany("Reservas")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("BackPredio11.Entities.Retirada", b =>
                {
                    b.HasOne("BackPredio11.Entities.MotivoRetirada", "MotivoRetirada")
                        .WithMany("Retiradas")
                        .HasForeignKey("MotivoRetiradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackPredio11.Entities.Pessoa", "Pessoa")
                        .WithMany("Retiradas")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MotivoRetirada");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("BackPredio11.Entities.MotivoRetirada", b =>
                {
                    b.Navigation("Retiradas");
                });

            modelBuilder.Entity("BackPredio11.Entities.Pessoa", b =>
                {
                    b.Navigation("Reservas");

                    b.Navigation("Retiradas");
                });
#pragma warning restore 612, 618
        }
    }
}
